/:
  controller: Base
  action: index

/contact:
  controller: Base
  action: contact


/mon-super-portfolio:
  controller: Base
  action: portfolio


/login:
  controller: Auth
  action: login

/logout:
    controller: Auth
    action: logout

/register:
  controller: Auth
  action: register

/confirm:
  controller: Auth
  action: confirm

/forgot-password:
  controller: Auth
  action: forgot

/reset-password:
  controller: Auth
  action: reset

/backoffice:
  controller: Admin
  action: index

/admin/users:
  controller: Admin
  action: users