/:
  controller: Base
  action: index

/contact:
  controller: Base
  action: contact

/portfolio:
  controller: Base
  action: portfolio


/login:
  controller: Auth
  action: login

/logout:
    controller: Auth
    action: logout

/register:
  controller: Auth
  action: register

/confirm:
  controller: Auth
  action: confirm

/forgot_password:
  controller: Auth
  action: forgot

/reset-password:
  controller: Auth
  action: reset



/backoffice:
  controller: Admin
  action: index

/dashboard:
  controller: Admin
  action: index



/admin/users:
  controller: Admin
  action: users

/admin/users/create:
  controller: Admin
  action: createUser

/admin/users/edit:
  controller: Admin
  action: editUser

/admin/users/delete:
  controller: Admin
  action: deleteUser



/admin/pages:
  controller: Admin
  action: pages

/admin/pages/create:
  controller: Admin
  action: createPage

/admin/pages/edit:
  controller: Admin
  action: editPage

/admin/pages/delete:
  controller: Admin
  action: deletePage


# Routes pour les utilisateurs normaux
/user/dashboard:
  controller: User
  action: dashboard

/my-pages:
  controller: User
  action: myPages

/my-pages/create:
  controller: User
  action: createPage

/my-pages/edit:
  controller: User
  action: editPage

/my-pages/delete:
  controller: User
  action: deletePage

/my-pages/view:
  controller: User
  action: viewPage